variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"
  CHECK_DIR: "$CI_PROJECT_DIR/ci/logs"
  BUILD_LOGS_DIR: "$CHECK_DIR/$CI_PROJECT_NAME.Rcheck"
  CRAN_REPOS: "https://cran.rstudio.com/"

image: rocker/tidyverse

stages:
  - init
  - check
  - test
  - deploy

initialize:
  stage: init
  script:
    - mkdir -p $R_LIBS_USER $BUILD_LOGS_DIR
    - cp .gitlab-ci/.Rprofile ./.Rprofile
    - Rscript -e 'remotes::install_deps(dependencies = TRUE, repos = Sys.getenv("CRAN_REPOS"), upgrade = TRUE, lib = Sys.getenv("R_LIBS_USER"))'
    - ls -ah $R_LIBS_USER
  cache:
    key: lib
    paths:
      - $R_LIBS_USER

checking:
  stage: check
  dependencies:
    - initialize
  script:
    - cp .gitlab-ci/.Rprofile ./.Rprofile
    - ls -ah $R_LIBS_USER
    - Rscript -e 'devtools::check(check_dir = Sys.getenv("CHECK_DIR"))'
    - Rscript -e 'if (length(devtools::check_failures(path = Sys.getenv("BUILD_LOGS_DIR"), note = FALSE)) > 0) stop()'
  cache:
    key: lib
    paths:
      - $R_LIBS_USER
    policy: pull

# To have the coverage percentage appear as a gitlab badge follow these
# instructions:
# https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing
# The coverage parsing string is
# Coverage: \d+\.\d+

testing:
  stage: test
  dependencies:
    - initialize
  allow_failure: true
  when: on_success
  only:
    - master
  script:
    - cp .gitlab-ci/.Rprofile ./.Rprofile
    - ls -ah $R_LIBS_USER
    - Rscript -e 'covr::gitlab(quiet = FALSE)'
  cache:
    key: lib
    paths:
      - $R_LIBS_USER
    policy: pull

pages:
  stage: deploy
  dependencies:
    - checking
  script:
    - cp .gitlab-ci/.Rprofile ./.Rprofile
    - ls -ah $R_LIBS_USER
    - Rscript -e 'remotes::install_local(dependencies = TRUE, repos = Sys.getenv("CRAN_REPOS"), force = TRUE, upgrade = TRUE)'
    - Rscript -e 'remotes::install_cran("pkgdown", repos = Sys.getenv("CRAN_REPOS"), force = FALSE, upgrade = TRUE, lib = Sys.getenv("R_LIBS_USER"))'
    - Rscript -e 'file.create("pkgdown.yml")'
    - mkdir public
    - cp pkgdown.yml public/
    - Rscript -e 'pkgdown::build_site(override = list(destination = "public"), preview=FALSE)'
  cache:
    key: lib
    paths:
      - $R_LIBS_USER
    policy: pull
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
