#' Propagate infections on the network
#'
#' For each infected node on the network, find susceptible neighbors and
#' probabilistically spread the infection.
#'
#' @param network An igraph network, generated by `create_network`
#' @param prob A probability matrix generated by `build_prob_matrix`
#' @param tracing Print informational messages about how many people were newly
#'   infected.
#'
#' @return A modified network graph after propagating the infections.
#' @examples
#' # ADD_EXAMPLES_HERE
#' @export
infect <- function(agents, neighbors, x0 = -2.556) {
  s_level <- get_seir_level("S")
  i_level <- get_seir_level("I")
  e_level <- get_seir_level("E")

  i_agents <- agents[seir == i_level, .(id, x_shed)]
  s_agents <- agents[seir == s_level, .(id, x_susc)]
  for (n in neighbors) {
    dt <- merge(i_agents, n, by.x = "id", by.y = "head")
    dt <- merge(dt, s_agents, by.x = "tail", by.y = "id")
    dt <- dt[, p := plogis(x0 + x_shed + x_susc + strength)]
    dt <- dt[, infect := purrr::rbernoulli(length(p), p)]
    if (any(dt$infect)) {
      infected <- dt[infect == TRUE, .(tail)]
      agents[id %in% infected$tail,
             c("seir", "ticks", "target") :=
               list(e_level, 0, set_target(.N, shape_ei, scale_ei))]
      s_agents <- s_agents[! id %in% infected$tail]
    }
  }
  invisible(agents)
}
