#' Propagate infections on the network
#'
#' For each infected node on the network, find susceptible neighbors and
#' probabilistically spread the infection.
#'
#' @param network An igraph network, generated by `create_network`
#' @param prob A probability matrix generated by `build_prob_matrix`
#' @param tracing Print informational messages about how many people were newly
#'   infected.
#'
#' @return A modified network graph after propagating the infections.
#' @examples
#' # ADD_EXAMPLES_HERE
#' @export
infect <- function(agents, edges, edge_params, tracing = FALSE) {
  infected <- 0
  level_s <- get_seir_level("S")
  level_e <- get_seir_level("E")
  level_i <- get_seir_level("I")

  i_agents <- agents[, seir == level_i]
  s_neighbors <- igraph::adjacent_vertices(network, i_vertices,
                                           mode = "all") %>%
    purrr::map(~.x[.x$seir == level_s])
  # message("length s_neighbors = ", purrr::map_int(s_neighbors, length) %>%
  #          stringr::str_c(collapse = ", "))
  for (i in seq_along(i_vertices)) {
    iv <- i_vertices[[i]]
    neighbors <- s_neighbors[[i]]
    neighbors <- neighbors[neighbors$seir == 1]
    # g_sn <<- s_neighbors
    if (length(neighbors) > 0) {
      i_probs <- get_prob(iv, neighbors, prob)
      # With probability i_probs, susceptible neighbors transition to exposed
      newly_infected <- neighbors[purrr::rbernoulli(length(i_probs), i_probs)]
      igraph::vertex_attr(network, "seir", newly_infected) <- level_e
      igraph::vertex_attr(network, "ticks", newly_infected) <- 0
      infected <- infected + length(newly_infected)
      # if (any(vertex_attr(network, "seir", neighbors) == level_e)) {
      #   message("Infected ",
      #           sum(vertex_attr(network, "seir", neighbors) == level_e),
      #           " neighbors, ", length(newly_infected), " newly infected.")
      # }
      # message("i = ", i, ", infected = ", infected)
      # s_neighbors <- purrr::map(s_neighbors, ~.x[!.x %in% newly_infected])
      #
      # message("length s_neighbors = ", purrr::map_int(s_neighbors, length) %>%
      #        stringr::str_c(collapse = ", "))
    }
  }
  if (tracing || .covidABM$tracing) {
    message(infected, " new transmissions.")
  }
  # gs_neighbors <<- s_neighbors
  invisible(network)
}

