#' Build a probability matrix for transmission of infection
#'
#' Take a data frame with columns corresponding to discrete coordinates in a
#' multidimensional space and form a matrix.
#'
#' @param prob_df A data frame with columns: Subject refers to the susceptible
#'   subject and agent refers to the infectious agent.
#'   * `sub_age_bkt` An ordered factor for age-bracket (lower = younger)
#'   * `sub_sex` A factor or character vector "F" or "M"
#'   * `sub_med_cond` Logical: Has pre-existing condition
#'   * `agt_age_bkt` An ordered factor for age-bracket.
#'   * `agt_sex`  A factor or character vector "F" or "M"
#'   * `agt_sympt` Logical: Does the agent display symptoms?
#'   * `prob` The probability of transmitting the infection from agent to
#'     subject.
#'
#' @return A 6-dimensional matrix.
#' @examples
#' # ADD_EXAMPLES_HERE
#' @export
build_prob_matrix <- function(prob_df) {
  age_brackets <- get("age_brackets", .covidABM)
  dims <- c(sub_age = max(age_brackets$bracket),
            sub_sex = 2,
            sub_med_cond = 2,
            agt_age = max(age_brackets$bracket),
            agt_sex = 2, agt_sympt = 2)
  sex <- factor(c("F", "M"))
  sympt <- factor(c("yes", "no"))
  med_cond <- factor(c("yes", "no"))
  prob_df <- prob_df %>%
    dplyr::select(.data$agt_sympt, .data$agt_sex, .data$agt_age_bkt,
                  .data$sub_med_cond, .data$sub_sex, .data$sub_age_bkt,
                  .data$prob) %>%
    dplyr::arrange(.data$agt_sympt, .data$agt_sex, .data$agt_age_bkt,
                   .data$sub_med_cond, .data$sub_sex, .data$sub_age_bkt)
  probs <- array(prob_df$prob, dim = dims,
                 dimnames = list(stringr::str_c("age_s_", seq(dims['sub_age'])),
                                stringr::str_c("sex_s_", levels(sex)),
                                stringr::str_c("cond_s_", levels(med_cond)),
                                stringr::str_c("age_a_", seq(dims['agt_age'])),
                                stringr::str_c("sex_a_", levels(sex)),
                                stringr::str_c("sympt_a_", levels(sympt))))
  invisible(probs)
}


#' Look up a disease-transmission probability
#'
#' Look up a disease-transmission probability from an infectious agent to a
#' susceptible subject, based on the characteristics of agent and subject.
#'
#' @param agent An agent (a row of an agents data frame or a vertex in an
#'   agent network) with `seir_status` = "I".
#' @param neighbors A list of neighbors (a data frame or list of neighboring
#'   vertices from the network graph).
#' @param probs A probability matrix generated by `build_prob_matrix`.
#'
#' @return A vector of probabilities corresponding to the list of neighbors.
#' @examples
#' # ADD_EXAMPLES_HERE
#' @export
get_prob <- function(agent, neighbors, probs) {
  # g_agt <<- agent
  # g_nbrs <<- neighbors
  idx <- function(obj, ...) { obj[...] }
  list(sub_age_bkt = neighbors$age_bkt, sub_sex = neighbors$sex,
       sub_med_cond = neighbors$med_cond,
       agt_age_bkt = agent$age_bkt, agt_sex = agent$sex,
       agt_sympt = agent$sympt) %>%
    tibble::as_tibble() %>% # dplyr::mutate_if(is.logical, ~1 + as.integer(.x)) %>%
    purrr::pmap_dbl(idx, obj = probs)
}


