#' Build a probability matrix for transitions between compartnemts
#'
#' Take a data frame with columns corresponding to discrete coordinates in a
#' multidimensional space and form a matrix.
#'
#' @param prob_df A data frame with columns:
#'   * `age_bkt` An ordered factor for age-bracket (lower = younger)
#'   * `sex` A factor or character vector "F" or "M"
#'   * `med_cond` Logical: Has pre-existing condition
#'   * `sympt` Logical: Does the agent display symptoms if infected?
#'   * `prob` The probability of transitioning to the next compartment
#'
#' @return A 4-dimensional matrix.
#' @examples
#' # ADD_EXAMPLES_HERE
#' @export
build_transition_matrix <- function(trans_df) {
  dims <- c(age = max(age_brackets$bracket),
            sex = 2,
            med_cond = 2,
            sympt = 2,
            var = 2)
  sex <- factor(c("F", "M"))
  sympt <- factor(c("no", "yes"))
  med_cond <- factor(c("no", "yes"))
  param <- factor(c("center", "scale"))
  par <- factor(trans_df$param) %>% unique()
  trans_df <- trans_df %>%
    select(param, sympt, med_cond, sex, age_bkt, value) %>%
    arrange(param, sympt, med_cond, sex, age_bkt)
  trans <- array(trans_df$value, dim = dims,
                 dimnames = list(str_c("age_", seq(dims['age'])),
                                 str_c("sex_", levels(sex)),
                                 str_c("cond_", levels(med_cond)),
                                 str_c("sympt_", levels(sympt)),
                                 str_c("par_", levels(par))))
  invisible(trans)
}


#' Look up a transition probability to the next compartment
#'
#' Look up a probability for an agent in compartment E or I to transition to
#' the next compartment (I or R, respectively), based on the characteristics of
#' agent and subject.
#'
#' @param agent An agent (a row of an agents data frame or a vertex in an
#'   agent network) with `seir_status` = "I".
#' @param neighbors A list of neighbors (a data frame or list of neighboring
#'   vertices from the network graph).
#' @param probs A transition probability matrix generated by
#'   `build_transition_matrix`.
#'
#' @return A vector of transition probabilities.
#' @examples
#' # ADD_EXAMPLES_HERE
#' @export
get_transition <- function(agent, transitions) {
  idx <- function(obj, ...) { obj[...] }
  indices <- list(age_bkt = agent$age_bkt, sex = agent$sex,
       med_cond = agent$med_cond,
       sympt = agent$sympt) %>%
    as_tibble() # %>% mutate_if(is.logical, ~1 + as.integer(.x))
  locs <- pmap_dbl(mutate(indices, var = 1), idx, obj = transitions)
  scales <- pmap_dbl(mutate(indices, var = 2), idx, obj = transitions)
  invisible(plogis(agent$ticks, locs, scales))
}
