#' Build a probability matrix for progression between compartnemts
#'
#' Take a data frame with columns corresponding to discrete coordinates in a
#' multidimensional space and form a matrix.
#'
#' @param prog_df A data frame with columns:
#'   * `age_bkt` An ordered factor for age-bracket (lower = younger)
#'   * `sex` A factor or character vector "F" or "M"
#'   * `med_cond` Logical: Has pre-existing condition
#'   * `sympt` Logical: Does the agent display symptoms if infected?
#'   * `prob` The probability of progressing to the next compartment
#'
#' @return A 4-dimensional matrix.
#' @examples
#' # ADD_EXAMPLES_HERE
#' @export
build_progression_matrix <- function(prog_df) {
  dims <- c(age = max(age_brackets$bracket),
            sex = 2,
            med_cond = 2,
            sympt = 2,
            var = 2)
  sex <- factor(c("F", "M"))
  sympt <- factor(c("no", "yes"))
  med_cond <- factor(c("no", "yes"))
  param <- factor(c("center", "scale"))
  par <- factor(prog_df$param) %>% unique()
  prog_df <- prog_df %>%
    dplyr::select(.data$param, .data$sympt, .data$med_cond, .data$sex,
                  .data$age_bkt, .data$value) %>%
    dplyr::arrange(.data$param, .data$sympt, .data$med_cond, .data$sex,
                   .data$age_bkt)
  prog <- array(prog_df$value, dim = dims,
                 dimnames = list(stringr::str_c("age_", seq(dims['age'])),
                                stringr::str_c("sex_", levels(sex)),
                                stringr::str_c("cond_", levels(med_cond)),
                                stringr::str_c("sympt_", levels(sympt)),
                                stringr::str_c("par_", levels(par))))
  invisible(prog)
}


#' Look up a progression probability to the next compartment
#'
#' Look up a probability for an agent in compartment E or I to progress to
#' the next compartment (I or R, respectively), based on the characteristics of
#' agent and subject.
#'
#' @param agent An agent (a row of an agents data frame or a vertex in an
#'   agent network) with `seir_status` = "I".
#' @param progressions A progression probability matrix generated by
#'   `build_progression_matrix`.
#'
#' @return A vector of progression probabilities.
#' @examples
#' # ADD_EXAMPLES_HERE
#' @export
get_progression <- function(agent, progressions) {
  idx <- function(obj, ...) { obj[...] }
  indices <- tibble::tibble(age_bkt = agent$age_bkt, sex = agent$sex,
                            med_cond = agent$med_cond, sympt = agent$sympt)
  locs <- purrr::pmap_dbl(dplyr::mutate(indices, var = 1),
                          idx, obj = progressions)
  scales <- purrr::pmap_dbl(dplyr::mutate(indices, var = 2),
                            idx, obj = progressions)
  invisible(stats::plogis(agent$ticks, locs, scales))
}
